name: pvcache
description: "A wrapper around HiveHook for Pathverse projects, providing secure and efficient caching solutions."
version: 1.0.1
homepage: https://github.com/Pathverse/pvcache

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  hivehook: ^0.1.7
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
