name: pvcache
description: "A new Flutter package project."
version: 1.0.0-dev.2
homepage: https://github.com/Pathverse/pvcache

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.4
  path: ^1.9.0
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  sembast_sqflite: ^2.2.0+2
  sqflite: ^2.4.1
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  

dev_dependencies:
  test: ^1.28.0
